name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
 
permissions: 
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    environment: $${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: $${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $${{ secrets.AZURE_TENANT_ID }}
          subscription-id: $${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ./infra/terraform/environments/$${{ inputs.environment }}
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: ./infra/terraform/environments/$${{ inputs.environment }}
        run: terraform plan

      
