name: Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-ci.yml'

  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terraform-ci.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ./infra

      - name: Terraform Init - Bootstrap
        working-directory: ./infra/bootstrap
        run: terraform init -backend=false

      - name: Terraform Validate - Bootstrap
        working-directory: ./infra/bootstrap
        run: terraform validate

      - name: Terraform Init - DEV
        working-directory: ./infra/terraform/environments/dev
        run: terraform validate